# Generated by Django 4.1 on 2022-08-08 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='uploads/images')),
                ('titre', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('Sportif', 'sportif'), ('Culturel', 'culturel')], max_length=200, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
